#pragma once
#include "MotionResolveShader.h"
// Uses the exact production pixel shader. Readback exists only in this test.
struct MotionPixelProbe {
    ComPtr<ID3D12RootSignature> root;
    ComPtr<ID3D12PipelineState> pso;
    ComPtr<ID3D12DescriptorHeap> rtv;
    ComPtr<ID3D12Resource> output,bias,readback,biasReadback;
    D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{},biasFp{};
    void Record(ID3D12Device* device,ID3D12GraphicsCommandList* cmd,D3D12_GPU_DESCRIPTOR_HANDLE inputs,ID3D12Resource* model,UINT w,UINT h,bool valid,ID3D12QueryHeap* queries){
        const char* vsCode="struct V{float4 pos:SV_Position;float2 uv:TEXCOORD0;}; V VS(uint id:SV_VertexID){V o;float2 uv=float2((id<<1)&2,id&2);o.uv=uv;o.pos=float4(uv.x*2-1,1-uv.y*2,0,1);return o;}";
        ComPtr<ID3DBlob> vs,ps,sig,err;hr(D3DCompile(vsCode,strlen(vsCode),nullptr,nullptr,nullptr,"VS","vs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&vs,&err));
        HRESULT result=D3DCompile(MotionResolveHlsl,strlen(MotionResolveHlsl),nullptr,nullptr,nullptr,"Raw","ps_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&ps,&err);if(FAILED(result)&&err)std::cerr<<(char*)err->GetBufferPointer();hr(result);
        D3D12_DESCRIPTOR_RANGE range{};range.RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_SRV;range.NumDescriptors=4;
        D3D12_ROOT_PARAMETER rp[3]{};rp[0].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp[0].DescriptorTable={1,&range};rp[0].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;
        rp[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;rp[1].Constants={0,0,4};rp[1].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;
        rp[2].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;rp[2].Descriptor.ShaderRegister=4;rp[2].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;
        D3D12_STATIC_SAMPLER_DESC sampler{};sampler.Filter=D3D12_FILTER_MIN_MAG_MIP_LINEAR;sampler.AddressU=sampler.AddressV=sampler.AddressW=D3D12_TEXTURE_ADDRESS_MODE_CLAMP;sampler.MaxLOD=D3D12_FLOAT32_MAX;sampler.ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;
        D3D12_ROOT_SIGNATURE_DESC rs{};rs.NumParameters=3;rs.pParameters=rp;rs.NumStaticSamplers=1;rs.pStaticSamplers=&sampler;rs.Flags=D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;
        hr(D3D12SerializeRootSignature(&rs,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&err));hr(device->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)));
        D3D12_GRAPHICS_PIPELINE_STATE_DESC desc{};desc.pRootSignature=root.Get();desc.VS={vs->GetBufferPointer(),vs->GetBufferSize()};desc.PS={ps->GetBufferPointer(),ps->GetBufferSize()};desc.BlendState.RenderTarget[0].RenderTargetWriteMask=desc.BlendState.RenderTarget[1].RenderTargetWriteMask=D3D12_COLOR_WRITE_ENABLE_ALL;desc.SampleMask=UINT_MAX;desc.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;desc.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;desc.RasterizerState.DepthClipEnable=TRUE;desc.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;desc.NumRenderTargets=2;desc.RTVFormats[0]=DXGI_FORMAT_R32G32_FLOAT;desc.RTVFormats[1]=DXGI_FORMAT_R32_FLOAT;desc.SampleDesc.Count=1;hr(device->CreateGraphicsPipelineState(&desc,IID_PPV_ARGS(&pso)));
        D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=2;hr(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&rtv)));const UINT rtvInc=device->GetDescriptorHandleIncrementSize(hd.Type);
        D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;auto texture=[&](DXGI_FORMAT format,ComPtr<ID3D12Resource>& out){D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=w;td.Height=h;td.DepthOrArraySize=1;td.MipLevels=1;td.SampleDesc.Count=1;td.Format=format;td.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_RENDER_TARGET,nullptr,IID_PPV_ARGS(&out)));return td;};auto td=texture(DXGI_FORMAT_R32G32_FLOAT,output);auto biasTd=texture(DXGI_FORMAT_R32_FLOAT,bias);auto handle=rtv->GetCPUDescriptorHandleForHeapStart();device->CreateRenderTargetView(output.Get(),nullptr,handle);D3D12_CPU_DESCRIPTOR_HANDLE biasHandle=handle;biasHandle.ptr+=rtvInc;device->CreateRenderTargetView(bias.Get(),nullptr,biasHandle);
        cmd->SetGraphicsRootSignature(root.Get());cmd->SetPipelineState(pso.Get());cmd->SetGraphicsRootDescriptorTable(0,inputs);float constants[4]={1,1,valid?1.f:0.f,0};cmd->SetGraphicsRoot32BitConstants(1,4,constants,0);cmd->SetGraphicsRootShaderResourceView(2,model->GetGPUVirtualAddress());cmd->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);D3D12_VIEWPORT vp{0,0,float(w),float(h),0,1};D3D12_RECT sc{0,0,LONG(w),LONG(h)};cmd->RSSetViewports(1,&vp);cmd->RSSetScissorRects(1,&sc);D3D12_CPU_DESCRIPTOR_HANDLE targets[]={handle,biasHandle};cmd->OMSetRenderTargets(2,targets,FALSE,nullptr);cmd->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,2);cmd->DrawInstanced(3,1,0,0);cmd->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,3);
        UINT rows;UINT64 rowBytes,total;device->GetCopyableFootprints(&td,0,1,0,&fp,&rows,&rowBytes,&total);readback=buffer(device,total,D3D12_HEAP_TYPE_READBACK);UINT biasRows;UINT64 biasRowBytes,biasTotal;device->GetCopyableFootprints(&biasTd,0,1,0,&biasFp,&biasRows,&biasRowBytes,&biasTotal);biasReadback=buffer(device,biasTotal,D3D12_HEAP_TYPE_READBACK);barrier(cmd,output.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE);barrier(cmd,bias.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE);D3D12_TEXTURE_COPY_LOCATION src{},dst{};src.pResource=output.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;dst.pResource=readback.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=fp;cmd->CopyTextureRegion(&dst,0,0,0,&src,nullptr);src.pResource=bias.Get();dst.pResource=biasReadback.Get();dst.PlacedFootprint=biasFp;cmd->CopyTextureRegion(&dst,0,0,0,&src,nullptr);
    }
    void Check(UINT x,UINT y,float vx,float vy){void* map;hr(readback->Map(0,nullptr,&map));auto row=reinterpret_cast<float*>(static_cast<uint8_t*>(map)+fp.Offset+y*fp.Footprint.RowPitch);const float ax=row[x*2],ay=row[x*2+1];readback->Unmap(0,nullptr);std::cout<<" pixel="<<ax<<","<<ay;check(std::abs(ax-vx)<.1f&&std::abs(ay-vy)<.1f,"Resolved motion in uniform area is wrong");}
    void CheckBias(UINT x,UINT y,float minimum){void* map;hr(biasReadback->Map(0,nullptr,&map));auto row=reinterpret_cast<float*>(static_cast<uint8_t*>(map)+biasFp.Offset+y*biasFp.Footprint.RowPitch);const float value=row[x];biasReadback->Unmap(0,nullptr);std::cout<<" bias="<<value;check(value>=minimum,"Disocclusion mask was not raised for new moving content");}
};
